import mongoose from "mongoose";
import dotenv from 'dotenv';
import Course from "./models/course.js";
import Blogs from "./models/blog.js";
import connectDB from "./config/db.js";
dotenv.config()
connectDB()
// Courses array
const courses = [
  {
    title: "Full Stack Web Development",
    image: "https://cdn-icons-png.flaticon.com/512/919/919825.png",
    description: "Master HTML, CSS, JavaScript, React, Node.js, MongoDB to build full-featured web applications.",
    duration: "12 Weeks",
    level: "Intermediate",
    price: "$199",
  },
  {
    title: "Python for Beginners",
    image: "https://cdn-icons-png.flaticon.com/512/1822/1822899.png",
    description: "Learn Python from scratch. Ideal for beginners with no prior experience.",
    duration: "8 Weeks",
    level: "Beginner",
    price: "Free",
  },
  {
    title: "React Mastery",
    image: "https://cdn-icons-png.flaticon.com/512/919/919851.png",
    description: "Deep dive into React with hooks, routing, API integration, and project-based learning.",
    duration: "6 Weeks",
    level: "Advanced",
    price: "$149",
  },
  {
    title: "Cybersecurity Essentials",
    image: "https://cdn-icons-png.flaticon.com/512/2659/2659362.png",
    description: "Learn the fundamentals of ethical hacking, networks, and system security.",
    duration: "10 Weeks",
    level: "Intermediate",
    price: "$249",
  },
  {
    title: "C++ Programming",
    image: "https://cdn-icons-png.flaticon.com/512/6132/6132221.png",
    description: "Understand object-oriented programming and data structures with C++.",
    duration: "10 Weeks",
    level: "Intermediate",
    price: "$129",
  },
  {
    title: "Java Programming",
    image: "https://cdn-icons-png.flaticon.com/512/226/226777.png",
    description: "Build robust applications with Java, including OOP, GUI, and backend.",
    duration: "10 Weeks",
    level: "Intermediate",
    price: "$149",
  },
  {
    title: "Data Science with Python",
    image: "https://cdn-icons-png.flaticon.com/512/2950/2950683.png",
    description: "Work on real datasets, visualization, pandas, NumPy, and machine learning basics.",
    duration: "12 Weeks",
    level: "Advanced",
    price: "$299",
  },
  {
    title: "MERN Stack Development",
    image: "https://cdn-icons-png.flaticon.com/512/919/919825.png",
    description: "Build powerful web apps using MongoDB, Express, React, and Node.js.",
    duration: "12 Weeks",
    level: "Advanced",
    price: "$199",
  },
  {
    title: "PHP & Laravel Development",
    image: "https://cdn-icons-png.flaticon.com/512/919/919825.png",
    description: "Develop backend systems and RESTful APIs using PHP and Laravel framework.",
    duration: "10 Weeks",
    level: "Intermediate",
    price: "$149",
  },
  {
    title: "Flutter Mobile Development",
    image: "https://cdn-icons-png.flaticon.com/512/919/919841.png",
    description: "Create beautiful Android & iOS apps with a single Flutter codebase.",
    duration: "8 Weeks",
    level: "Intermediate",
    price: "$179",
  },
  {
    title: "JavaScript Essentials",
    image: "https://cdn-icons-png.flaticon.com/512/919/919828.png",
    description: "Cover the fundamentals of JavaScript, including DOM, events, and ES6+.",
    duration: "6 Weeks",
    level: "Beginner",
    price: "Free",
  },
  {
    title: "Web Design with HTML & CSS",
    image: "https://cdn-icons-png.flaticon.com/512/1006/1006771.png",
    description: "Design beautiful and responsive websites using HTML5 and modern CSS.",
    duration: "6 Weeks",
    level: "Beginner",
    price: "$99",
  },
  {
    title: "Excel Programming & Automation",
    image: "https://cdn-icons-png.flaticon.com/512/732/732220.png",
    description: "Automate reports, build dashboards, and analyze data using Excel VBA.",
    duration: "5 Weeks",
    level: "Intermediate",
    price: "$89",
  },
  {
    title: "Android Development with Kotlin",
    image: "https://cdn-icons-png.flaticon.com/512/888/888857.png",
    description: "Learn to build native Android apps with Kotlin and Android Studio.",
    duration: "10 Weeks",
    level: "Intermediate",
    price: "$199",
  },
  {
    title: "Graphics Design Masterclass",
    image: "https://cdn-icons-png.flaticon.com/512/2913/2913469.png",
    description: "Create stunning designs using Photoshop, Illustrator, and Canva.",
    duration: "8 Weeks",
    level: "Beginner",
    price: "$119",
  },
  {
    title: "AutoCAD for Civil Engineering",
    image: "https://cdn-icons-png.flaticon.com/512/355/355980.png",
    description: "Design roads, drainage, and buildings using AutoCAD tools.",
    duration: "6 Weeks",
    level: "Intermediate",
    price: "$149",
  },
  {
    title: "CCNA Networking Fundamentals",
    image: "https://cdn-icons-png.flaticon.com/512/1055/1055646.png",
    description: "Understand the core of networking: IP, routing, switching, and security.",
    duration: "10 Weeks",
    level: "Advanced",
    price: "$199",
  },
  {
    title: "Quality Assurance & Testing",
    image: "https://cdn-icons-png.flaticon.com/512/2659/2659445.png",
    description: "Learn manual & automated testing using Selenium, JUnit, and more.",
    duration: "7 Weeks",
    level: "Intermediate",
    price: "$149",
  },
  {
    title: "C Programming Foundations",
    image: "https://cdn-icons-png.flaticon.com/512/6132/6132221.png",
    description: "Understand low-level programming, memory, and logic using C.",
    duration: "6 Weeks",
    level: "Beginner",
    price: "Free",
  },
  {
    title: "Microsoft SQL Server Essentials",
    image: "https://cdn-icons-png.flaticon.com/512/919/919836.png",
    description: "Manage relational databases and write powerful SQL queries.",
    duration: "8 Weeks",
    level: "Intermediate",
    price: "$129",
  }
];
const blogData = [
  {
    title: "Getting Started with React Hooks",
    date: "August 2, 2025",
    tags: ["React", "Web Development"],
    category: "React",
    author: "John Doe",
    image: "https://miro.medium.com/v2/resize:fit:1100/format:webp/1*cPh7ujRIfcHAy4kW2ADGOw.png",
    excerpt: "Learn how to use React Hooks like useState and useEffect in functional components.",
  },
  {
    title: "Understanding the OSI Model in Networking",
    date: "July 28, 2025",
    tags: ["Networking", "CCNA"],
    category: "Networking",
    author: "Jane Smith",
    image: "https://www.auvik.com/wp-content/uploads/2020/06/osi-model.png",
    excerpt: "A beginner-friendly breakdown of the 7 layers of the OSI model with practical examples.",
  },
  {
    title: "10 Python Tricks Every Developer Should Know",
    date: "July 21, 2025",
    tags: ["Python", "Programming"],
    category: "Python",
    author: "Alex Turner",
    image: "https://miro.medium.com/v2/resize:fit:1100/format:webp/1*Z1E2NQjcyE-uSRgMEcODdw.png",
    excerpt: "Enhance your Python code with 10 useful tricks and best practices.",
  },
  {
    title: "Career Tips for Aspiring Software Engineers",
    date: "July 14, 2025",
    tags: ["Career Tips", "Software Engineering"],
    category: "Career Tips",
    author: "Priya Karki",
    image: "https://res.cloudinary.com/ds6spmr71/image/upload/v1677695159/software_engineer_tips.jpg",
    excerpt: "Explore valuable career tips for landing your dream software engineering job.",
  },
  {
    title: "Introduction to Artificial Intelligence: Concepts & Applications",
    date: "August 5, 2025",
    tags: ["AI", "Machine Learning"],
    category: "AI",
    author: "Sophia Rai",
    image: "https://cdn-icons-png.flaticon.com/512/4712/4712100.png",
    excerpt: "Explore core concepts of AI and real-world applications shaping automation.",
  },
  {
    title: "Mastering CSS Grid and Flexbox",
    date: "August 10, 2025",
    tags: ["Web Development", "CSS"],
    category: "Web Development",
    author: "Michael Lee",
    image: "https://miro.medium.com/max/1400/1*Z0O6TQ1V2ZVhQ8Hj6Q75Rg.png",
    excerpt: "Learn how to create modern, responsive layouts using CSS Grid and Flexbox.",
  },
  {
    title: "Deep Dive into JavaScript ES6 Features",
    date: "August 12, 2025",
    tags: ["JavaScript", "Web Development"],
    category: "Web Development",
    author: "Emma Watson",
    image: "https://cdn-icons-png.flaticon.com/512/5968/5968292.png",
    excerpt: "Understand ES6 features like arrow functions, destructuring, and modules.",
  },
  {
    title: "React Router: Navigating Single Page Applications",
    date: "August 15, 2025",
    tags: ["React", "Web Development"],
    category: "React",
    author: "John Doe",
    image: "https://reactrouter.com/_brand/react-router-stacked-color.png",
    excerpt: "Learn routing in React apps using React Router for dynamic navigation.",
  },
  {
    title: "Building RESTful APIs with Node.js and Express",
    date: "August 18, 2025",
    tags: ["Node.js", "Web Development", "Backend"],
    category: "Web Development",
    author: "Jane Smith",
    image: "https://nodejs.org/static/images/logo.svg",
    excerpt: "Step-by-step guide to creating RESTful APIs using Node.js and Express.",
  },
  {
    title: "Understanding TCP/IP Protocols",
    date: "August 20, 2025",
    tags: ["Networking", "CCNA"],
    category: "Networking",
    author: "Alex Turner",
    image: "https://www.cisco.com/c/en/us/solutions/collateral/enterprise-networks/what-is-tcp-ip/white-paper-c11-741957.png",
    excerpt: "Learn the core TCP/IP protocols and their role in networking communication.",
  },
  {
    title: "Python for Data Science: NumPy & Pandas",
    date: "August 22, 2025",
    tags: ["Python", "Data Science"],
    category: "Python",
    author: "Priya Karki",
    image: "https://miro.medium.com/max/1400/1*_ny6GqXY0D0M0A4tYm2uhQ.png",
    excerpt: "Use Python libraries like NumPy and Pandas to manipulate and analyze data.",
  },
  {
    title: "Machine Learning Basics with scikit-learn",
    date: "August 25, 2025",
    tags: ["AI", "Machine Learning", "Python"],
    category: "AI",
    author: "Sophia Rai",
    image: "https://scikit-learn.org/stable/_static/scikit-learn-logo-small.png",
    excerpt: "An introduction to machine learning concepts and scikit-learn library in Python.",
  },
  {
    title: "Advanced Python: Decorators and Generators",
    date: "August 28, 2025",
    tags: ["Python", "Programming"],
    category: "Python",
    author: "Michael Lee",
    image: "https://miro.medium.com/max/1400/1*bOXnE0O6DNN7GqPaDQXZ0A.png",
    excerpt: "Learn advanced Python concepts like decorators and generators for efficient coding.",
  },
  {
    title: "Front-end Performance Optimization Tips",
    date: "August 30, 2025",
    tags: ["Web Development", "React"],
    category: "Web Development",
    author: "Emma Watson",
    image: "https://miro.medium.com/max/1400/1*BlV0t9TITsIFrN-3EIEKtw.png",
    excerpt: "Techniques to optimize front-end performance and reduce page load times.",
  },
  {
    title: "CCNA Routing & Switching Essentials",
    date: "September 1, 2025",
    tags: ["Networking", "CCNA"],
    category: "Networking",
    author: "John Doe",
    image: "https://www.cisco.com/c/dam/en_us/training-events/images/ccna-logo.png",
    excerpt: "Comprehensive guide to CCNA Routing and Switching essentials.",
  },
  {
    title: "Python Web Scraping with BeautifulSoup",
    date: "September 3, 2025",
    tags: ["Python", "Web Development"],
    category: "Python",
    author: "Jane Smith",
    image: "https://miro.medium.com/max/1400/1*6Eyy5H1Rv1mE7kqI7d2UKQ.png",
    excerpt: "Learn to extract data from websites using Python and BeautifulSoup.",
  },
  {
    title: "React State Management with Context API",
    date: "September 5, 2025",
    tags: ["React", "Web Development"],
    category: "React",
    author: "Alex Turner",
    image: "https://reactjs.org/logo-og.png",
    excerpt: "Manage React state efficiently using Context API in functional components.",
  },
  {
    title: "Building Secure APIs with JWT Authentication",
    date: "September 7, 2025",
    tags: ["Node.js", "Web Development", "Security"],
    category: "Web Development",
    author: "Priya Karki",
    image: "https://jwt.io/img/pic-logo.svg",
    excerpt: "Secure your Node.js APIs using JWT authentication techniques.",
  },
  {
    title: "Introduction to Cloud Computing",
    date: "September 10, 2025",
    tags: ["Cloud", "Tech Trends"],
    category: "Web Development",
    author: "Sophia Rai",
    image: "https://miro.medium.com/max/1400/1*5RJbyQzT8vFvc2Yl7UqPhg.png",
    excerpt: "Understand cloud computing concepts and popular cloud platforms.",
  },
  {
    title: "Python Data Visualization with Matplotlib",
    date: "September 12, 2025",
    tags: ["Python", "Data Science"],
    category: "Python",
    author: "Michael Lee",
    image: "https://matplotlib.org/_static/images/logo2.svg",
    excerpt: "Visualize data in Python using Matplotlib for graphs and charts.",
  },]
const seedCourses = async () => {
  try {
    await connectDB();
    await Blogs.deleteMany(); // clear old data
    await Blogs.insertMany(blogData);
    console.log("Blogs inserted successfully!");
    process.exit();
  } catch (error) {
    console.error("Error inserting courses:", error);
    process.exit(1);
  }
};

seedCourses();